//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSOFOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartDetail
    {
        public int sno { get; set; }
        public int MenuItemId { get; set; }
        public string MenuItemName { get; set; }
        public string MenuItemDescription { get; set; }
        public string MenuItemImage { get; set; }
        public int Amount { get; set; }
        public int Quantity { get; set; }
        public string CategoryId { get; set; }
        public string EmailId { get; set; }
    
        public virtual MenuItem MenuItem { get; set; }
    }
}
