//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSOFOS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Feedback
    {
        public int FeedbackId { get; set; }
        [Required(ErrorMessage = "Enter Feedback")]
        [Display(Name = "Feedback")]
        public string Feedback1 { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        [Required(ErrorMessage = "Choose date")]
        [Display(Name = "CreatedAt")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string UserName { get; set; }
    
        public virtual UserMaster UserMaster { get; set; }
    }
}
