//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSOFOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderId { get; set; }
        public string OrderDisplayNo { get; set; }
        public Nullable<int> MenuItemId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Status { get; set; }
        public Nullable<int> PaymentId { get; set; }
        public Nullable<int> RestaurantId { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual MenuItem MenuItem { get; set; }
        public virtual Payment Payment { get; set; }
        public virtual Restaurant Restaurant { get; set; }
        public virtual UserMaster UserMaster { get; set; }
    }
}
