//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSOFOS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Restaurant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Restaurant()
        {
            this.Categories = new HashSet<Category>();
            this.Orders = new HashSet<Order>();
        }
    
        public int RestaurantId { get; set; }
       // [Required(ErrorMessage = "Enter Restaurant name")]
        public string RestaurantName { get; set; }
        //[Required(ErrorMessage = "Select Category")]
        public Nullable<int> CategoryId { get; set; }
        
        public string RestaurantImage { get; set; }
        //[Required(ErrorMessage = "Enter Description")]
        //[Display(Name = "Description")]
        public string RestaurantDescription { get; set; }
        public bool IsActive { get; set; }
        //[Required(ErrorMessage = "Enter OpenTime")]
        //[Display(Name = "OpenTime")]
        public string OpenTime { get; set; }
        public string CloseTime { get; set; }

        [Required(ErrorMessage = "Choose time")]
        [Display(Name = "StartTime")]
        [DataType(DataType.Time)]
        public Nullable<System.DateTime> startTime { get; set; }
        [Required(ErrorMessage = "Choose time")]
        [Display(Name = "EndTime")]
        [DataType(DataType.Time)]
        public Nullable<System.DateTime> endTime { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Category> Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
